### ISSUE TITLE
Migrate docs website to Vercel

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#1171]
# Details

We now have access to the PSE Vercel account 🎉 - let's migrate the website over to Vercel

**MACI website: Current setup**

- Preview deploys on Netlify
- Production deploys on GH pages

**MACI website: Migration to Vercel**

- Preview deploys on Vercel
- Production deploys on Vercel

## TODO
- [x] Move docs website over to Vercel
- [x] Configure PR preview deploys (https://vercel.com/docs/deployments/preview-deployments)
- [x] Remove Netlify GH integration
- [ ] @baumstern cancel personal Netlify account

**Comment by samajammin** [comment]
> @0xmad any update on this? :)

@baumstern we're working on it this sprint!

**Comment by 0xmad** [comment]
@baumstern it's done, you can cancel your Netlify account
